" Based on https://missing.csail.mit.edu/2020/editors/ example

" Set leader key
let mapleader = ","

" It's a good idea to set nocompatible:
" https://stackoverflow.com/a/22543937
set nocompatible

" Syntax hilighting
syntax on

" Disable startup message
"set shortmess+=I

" Show line numbers
set number
" Set relative line numbering for easier navigation
set relativenumber

" More intuitive backspace behaviour
set backspace=indent,eol,start

" Unbind some useless/annoying default key bindings.
nmap Q <Nop>

" Mouse support
set mouse+=a

" Search while typing + smart case matching
set incsearch
set ignorecase
set smartcase

" Spaces instead of tabs and other indentation
filetype on
filetype plugin on
filetype indent on
set autoindent
set expandtab
set tabstop=2 shiftwidth=2
"set smarttab
set shiftround

" don't break words
set linebreak

" Show colorcolumn on `textwidth`
set colorcolumn=+0

" Make :W save (I often hit this accidentally as ':' is produced with Shift key)
command W w
command Wq wq
command WQ wq
command Q q

" Fix missing symbols
let g:airline_powerline_fonts = 1

" emmet-vim
" default unless leader is set: Ctrl-Y + ,
let g:user_emmet_leader_key='<leader><leader>' " ,,, -> html completion
" vimtex config
let g:tex_flavor = "latex"
nnoremap <F5> :VimtexCompile<CR>

" the delay after pressing esc in insert mode is annoying
set timeoutlen=1000 ttimeoutlen=0

" disable 'Press ENTER or type command to continue' when remote editing
:let g:netrw_silent=1

" syntax highlighting in markdown code blocks
let g:markdown_fenced_languages = ['sh', 'bash=sh', 'python', 'html', 'javascript']

" toggle NERDTree, inspiration from
" https://tuckerchapman.com/2018/06/16/how-to-use-the-vim-leader-key/
map <leader>t :NERDTreeToggle<CR>

map <leader>nh :noh<CR>

nnoremap <leader>aa ggVG
nnoremap <leader>ca ggVGc
nnoremap <leader>ya msggVG"+yg`s:delmark s<CR>:echo 'Copied buffer content to +'<CR>

map <leader>sp :set spell!<CR>

" auto-pairs
let g:AutoPairsShortcutToggle = '<leader>p'

map <leader>bn :bn<CR>
map <leader>bp :bp<CR>
