" Based on https://missing.csail.mit.edu/2020/editors/ example

" Set leader key
let mapleader = ","

" It's a good idea to set nocompatible:
" https://stackoverflow.com/a/22543937
set nocompatible

" Syntax hilighting
syntax on

" Disable startup message
"set shortmess+=I

" Show line numbers
set number
" Set relative line numbering for easier navigation
set relativenumber

" More intuitive backspace behaviour
set backspace=indent,eol,start

" Unbind some useless/annoying default key bindings.
nmap Q <Nop>

" Mouse support
set mouse+=a

" Search while typing + smart case matching
set incsearch
set ignorecase
set smartcase

" Spaces instead of tabs and other indentation
filetype on
filetype plugin on
filetype indent on
set autoindent
set expandtab
set tabstop=4 shiftwidth=4
"set smarttab
set shiftround

" Make :W save (I often hit this accidentally as ':' is produced with Shift key)
command W w
command Wq wq
command WQ wq

" Fix missing symbols
let g:airline_powerline_fonts = 1

" emmet-vim
let g:user_emmet_leader_key=','

" vimtex config
let g:tex_flavor = "latex"
nnoremap <F5> :VimtexCompile<CR>

" background
" does not work with multiple tabs
let t:is_light = 0
function! ToggleBackground()
    if t:is_light == 0
        set background=light
        AirlineTheme light
        let t:is_light = 1
        echom "background is set to light"
    else
        set background=dark
        AirlineTheme dark
        let t:is_light = 0
        echom "background is set to dark"
    endif
endfunction
" Execute ToggleBackground just after initializing vim
" https://stackoverflow.com/a/6821698
autocmd VimEnter * silent call ToggleBackground()
nnoremap <F12> :call ToggleBackground()<CR>
inoremap <F12> <Esc>:call ToggleBackground()<CR>a

" vim-airline

" use tabline
let g:airline#extensions#tabline#enabled = 1
" the delay after pressing esc in insert mode is annoying
set timeoutlen=1000 ttimeoutlen=0

" disable 'Press ENTER or type command to continue' when remote editing
:let g:netrw_silent=1

" syntax highlighting in markdown code blocks
let g:markdown_fenced_languages = ['sh', 'bash=sh', 'python', 'html', 'javascript']

" toggle NERDTree, inspiration from
" https://tuckerchapman.com/2018/06/16/how-to-use-the-vim-leader-key/
map <leader>t :NERDTreeToggle<CR>
