#! /bin/sh

# start necessary processes
# keybindings
sxhkd &
# compositor
picom --experimental-backend &

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# gaps & borders
bspc config border_width         6
bspc config window_gap          12

# colors
bspc config normal_border_color   '#cfcbd0'
bspc config active_border_color   '#777777'
bspc config focused_border_color  '#777777'

# windows
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# window rules
bspc rule -a 'plasmashell' state=floating layer=above focus=off sticky=on border=off center=off
bspc rule -a Gimp state=floating follow=on

# do not overlap with the top bar
bspc config top_padding $((48 + 24))
