FROM opensuse/tumbleweed

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

COPY --from=install_scripts . /usr/local/bin/

# Install dependencies
RUN zypper refresh && \
    zypper install -y \
      nodejs npm \
      ShellCheck \
      awk \
      bash \
      diffutils \
      envsubst \
      file \
      findutils \
      gcc \
      git \
      jq \
      luajit-lpeg \
      neovim \
      python3 \
      sqlite3-devel \
      tar \
      tree \
      tree-sitter \
      which \
      yq \
      zsh \
    && zypper clean -a

RUN useradd cla -m -s /bin/zsh

# Comment/uncomment below
RUN cla_install_claude_code.sh
RUN cla_install_flutter.sh
RUN cla_install_pnpm.sh
RUN cla_install_samporapeli_dotfiles.sh

# Claude Code
ENV PATH="/home/cla/.local/bin:$PATH"
ENV CLAUDE_CODE_DISABLE_AUTO_UPDATE=1
ENV CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

USER cla

# Set up working directory
WORKDIR /workspace

CMD ["/bin/zsh"]
