FROM opensuse/tumbleweed

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

COPY --from=install-scripts . /usr/local/bin/

# Install dependencies
RUN zypper refresh && \
    zypper install -y \
      nodejs npm \
      git \
      file \
      diffutils \
      envsubst \
      findutils \
      tar \
      tree \
      bash \
      jq \
      zsh \
      python3 \
      sqlite3-devel \
      which \
      nvim \
      vim \
    && zypper clean -a

RUN useradd claude -m -s /bin/zsh

# Comment/uncomment below
RUN cla_install_pnpm.sh
RUN cla_install_flutter.sh

USER claude

# Install dotfiles
RUN cd /home/claude && SAMPORAPELI_DOTFILES_UNATTENDED_INSTALL=true bash <(curl -sL sampo.website/install-dotfiles.sh)

# Install Claude Code
RUN curl -fsSL https://claude.ai/install.sh | bash
ENV PATH="/home/claude/.local/bin:$PATH"

ENV CLAUDE_CODE_DISABLE_AUTO_UPDATE=1
ENV CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

# Set up working directory
WORKDIR /workspace

CMD ["/bin/zsh"]
